config/routes.rb
RedditOnRails::Application.routes.draw do
  devise_for :users
  
  get 'search' => 'search#index'
  root :to => "pages#index"
  resources :pages, :links, :comments, :votes
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :message, :user_id, :link_id
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :title, :url
  belongs_to :user
  has_many :comments
  has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :title, :body, :email, :username
  
  has_many :links
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :user_id, :link_id, :up
  
  validates :user_id, :uniqueness => { :scope => :link_id }
  
  belongs_to :user
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @comment = current_user.comments.create(params[:comment])
    redirect_to :back
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @link = Link.where(id: params[:id]).first
    @comment = Comment.new
  end
  
  def new
    @link = Link.new
  end
  
def create
    @link = current_user.links.create(params[:link])
    redirect_to link_path(id: @link.id)
 end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    params[:per_page] ||= 25
    params[:page] ||= 1
    @links = Link.order('created_at DESC').page(params[:page]).per_page(params[:per_page])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @links = Link.search(:title => params[:q]).page(params[:page]).per_page(2)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @vote = Vote.where(user_id: current_user.id, link_id: params[:vote][:link_id]).first
    if @vote
      @vote.up = params[:vote][:up]
      @vote.save
    else
      @vote = current_user.votes.create(params[:vote])
    end
    
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
  <title>RedditOnRails</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>


    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <%= stylesheet_link_tag    "application", :media => "all" %>

    <script src="http://heroku.github.com/template-app-bootstrap/jquery-1.7.1.min.js"></script>
    <script src="http://heroku.github.com/template-app-bootstrap/jquery.replacetext.min.js"></script>

    <!--
      IMPORTANT:
      This is Heroku specific styling. Remove to customize.
    -->
    <link href="http://heroku.github.com/template-app-bootstrap/heroku.css" rel="stylesheet">
    <!-- /// -->

    <!--
      IMPORTANT:
      To do the replacement  example for the real name application
    -->
    <script src="http://heroku.github.com/template-app-bootstrap/heroku.js"></script>
    <!-- /// -->


  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a href="/" class="brand">Reddit on Rails</a>
          <div class='nav'>
            <ul class='nav'>
              <%# user is logged in, show log out link %>
              <% if current_user.present? %>
                <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
              <%# user is not logged in, show signup and login links %>
              <% else %>
                <li><%= link_to 'Sign In', new_user_session_path %></li> |
                <li><%= link_to 'Register Now!', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
          
          <%= form_tag(search_path, :method => "get", :style => "margin: 5px 0 0 0") do %>
  <%= text_field_tag(:q, nil, :placeholder => "search") %>
  <%= submit_tag("Search") %>
<% end %>

          <!--
            IMPORTANT:
            This is Heroku specific markup. Remove to customize.
          -->
          <a href="/" class="brand" id="heroku">by <strong>heroku</strong></a>
          <!-- /// -->
        </div>
      </div>
    </div>

    <% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div data-alert="alert" class="alert alert-<%= level %> fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>
    
    <div class="container" id="getting-started">
      <div class="row">
        <div class="span6 offset2">
        <div class="page-header"></div>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/links/create.html.erb
created: 

<%= @link.inspect %>

app/views/links/new.html.erb
<%= form_for(@link) do |f| %>
 <% if @link.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

     <ul>
     <% @link.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
   <%= f.label :url %><br />
   <%= f.text_field :url %>
 </div>
 <div class="field">
   <%= f.label :title %><br />
   <%= f.text_field :title %>
 </div>
 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/links/show.html.erb
<h2>Link title: <%= @link.title %></h2>
<h2>Link url: <%= @link.url %></h2>

<div>
  <% @link.comments.each do |x| %>
    <p><%= x.message %></p>
  <% end %>
  
</div>

<%= form_for(@comment) do |f| %>
 <% if @comment.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

     <ul>
     <% @comment.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
   <%= f.label :message %><br />
   <%= f.text_area :message, :placeholder => "Add a comment" %>
 </div>

 <%= f.hidden_field :link_id, :value => @link.id %>
 
 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/pages/index.html.erb
<h2>Homepage</h2>

<%= link_to "Add a link", new_link_path %>

<%= will_paginate @links %>

<ul>
  <% @links.each do |x| %>
    <li>
      <% if current_user && current_user.votes.where(link_id: x.id, up: true).present? %>
        *
      <% else %>
        <%= link_to "+", votes_path(:vote => {:link_id => x.id, :up => true}), :method => :post %>
      <% end %>
        /
      <% if current_user && current_user.votes.where(link_id: x.id, up: false).present? %>
        *
      <% else %>
        <%= link_to "-", votes_path(:vote => {:link_id => x.id, :up => false}), :method => :post %>
      <% end %>
      | Vote count: <%= x.votes.where(up: true).count - x.votes.where(up: false).count %> | <%= link_to x.title, x.url %> | <%= link_to "comments", x %>
      </li>
  <% end %>
</ul>

app/views/search/index.html.erb
<%= will_paginate @links %>

Here are all the links that matched "<%= params[:q] %>"
<ul>
  <% for link in @links do %>
    <li>
      Votes: <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %>
      
      <% if current_user && current_user.votes.where(:link_id => link.id, :up => true).present? %>
        *
      <% else %>
        <%= link_to('+', votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post) %>
      <% end %>
      
      <% if current_user && current_user.votes.where(:link_id => link.id, :up => false).present? %>
        *
      <% else %>
        <%= link_to('-', votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post) %>
      <% end %>
      
      <%= link_to(link.title, link.url) %>
      <%= link_to('comments', link) %>
      
    </li>
  <% end %>
</ul>